;;;
;;;; CUSTOMIZE VARIABLES
;;;=====================
(custom-set-variables
  ;; custom-set-variables was added by Custom.
  ;; If you edit it by hand, you could mess it up, so be careful.
  ;; Your init file should contain only one such instance.
  ;; If there is more than one, they won't work right.
 '(Buffer-menu-buffer+size-width 36)
 '(Buffer-menu-mode-width 10)
 '(TeX-view-program-selection (quote (((output-dvi style-pstricks) "dvips and start") (output-dvi "Yap") (output-pdf "Sumatra PDF") (output-html "start"))))
 '(align-to-tab-stop nil)
 '(archive-zip-extract (quote ("C:\\Program Files (x86)\\WinZip\\Wzunzip.EXE" "-yb" "-c")))
 '(auto-revert-interval 60)
 '(auto-save-timeout 120)
 '(bibtex-maintain-sorted-entries (quote entry-class))
 '(browse-kill-ring-highlight-current-entry t)
 '(browse-kill-ring-highlight-inserted-item t)
 '(case-fold-search t)
 '(comment-column 50)
 '(completion-ignored-extensions (quote (".o" "~" ".obj" ".elc")))
 '(cperl-invalid-face nil)
 '(desktop-lazy-verbose nil)
 '(directory-abbrev-alist nil)
 '(dired-omit-files "^\\.?#\\|^\\.")
 '(display-buffer-reuse-frames t)
 '(doxymacs-blank-multiline-comment-template (quote ("/**" > n "  " p > n "  " > n "*/" > n)))
 '(doxymacs-doxygen-style "JavaDoc")
 '(edebug-trace nil)
 '(enable-local-eval t)
 '(ff-quiet-mode t)
 '(find-ls-option (quote ("-exec ls -ld {} ';'" . "-ld")))
 '(globalff-regexp-search t)
 '(history-delete-duplicates t)
 '(history-length 100)
 '(imenu-tree-auto-update t)
 '(indent-tabs-mode nil)
 '(inhibit-startup-screen t)
 '(iswitchb-default-method (quote maybe-frame))
 '(iswitchb-mode t nil (iswitchb))
 '(jit-lock-stealth-load 90)
 '(kill-whole-line t)
 '(line-number-display-limit-width 400)
 '(locate-command "locate_windows")
 '(ls-lisp-dirs-first t)
 '(ls-lisp-emulation (quote MS-Windows))
 '(ls-lisp-ignore-case t)
 '(ls-lisp-verbosity nil)
 '(mac-emulate-three-button-mouse t)
 '(matlab-vers-on-startup nil)
 '(mediawiki-site-alist (quote (("Wikipedia" "http://en.wikipedia.org/w/" "username" "password" "Main Page") ("qw" "http://qa.barcapint.com:8080/wiki/" "JonathanMoore" "moorjona" "Main Page"))))
 '(minibuffer-prompt-properties (quote (read-only t point-entered minibuffer-avoid-prompt face minibuffer-prompt)))
 '(next-line-add-newlines nil)
 '(org-agenda-files (quote ("~/org")))
 '(org-agenda-start-with-clockreport-mode nil)
 '(org-drawers (quote ("PROPERTIES" "CLOCK" "LOGBOOK" "RESULTS" "EMAIL")))
 '(partial-completion-mode t nil (complete))
 '(perlnow-perl-module-template (concat emacs-root "/site-lisp/templates"))
 '(perltidy-program "c:\\p4ws\\depot\\QA\\ThirdParty\\Perl\\Perl-Tidy\\20071205\\bin\\perltidy.bat")
 '(ps-font-size (quote (8 . 8.5)))
 '(ps-print-color-p (quote black-white))
 '(reftex-bibpath-environment-variables (quote ("BIBINPUTS" "TEXBIB" "c:/latex/")))
 '(reftex-toc-split-windows-horizontally t)
 '(safe-local-variable-values (quote ((generated-autoload-file concat emacs-root "/site-lisp/jnm-loaddefs.el") (generated-autoload-file concat emacs-root "/site-lisp/jm-loaddefs.el"))))
 '(set-mark-command-repeat-pop t)
 '(sgml-basic-offset 8)
 '(show-paren-style (quote expression))
 '(show-trailing-whitespace nil)
 '(transient-mark-mode t)
 '(truncate-partial-width-windows nil)
 '(vc-annotate-display-mode (quote fullscale))
 '(w32-list-proportional-fonts t t)
 '(warning-suppress-types (quote ((undo discard-info))))
 '(which-func-modes (quote (c-mode perl-mode cperl-mode python-mode makefile-mode sh-mode diff-mode)))
 '(woman-imenu t)
 '(woman-use-own-frame nil)
 '(woman-use-topic-at-point t)
 '(woman-use-topic-at-point-default t))

(custom-set-faces
  ;; custom-set-faces was added by Custom.
  ;; If you edit it by hand, you could mess it up, so be careful.
  ;; Your init file should contain only one such instance.
  ;; If there is more than one, they won't work right.
 '(default ((t (:inherit nil :stipple nil :background "blue4" :foreground "white" :inverse-video nil :box nil :strike-through nil :overline nil :underline nil :slant normal :weight normal :height 120 :width normal :foundry "outline" :family "Consolas"))))
 '(font-lock-builtin-face ((((class color) (background light)) (:foreground "blue"))))
 '(font-lock-comment-face ((t (:foreground "sky blue"))))
 '(font-lock-constant-face ((((class color) (background light)) (:foreground "dark green"))))
 '(font-lock-function-name-face ((((class color) (background light)) (:foreground "Blue"))))
 '(font-lock-string-face ((((class color) (background light)) (:foreground "purple4"))))
 '(font-lock-type-face ((((class color) (background light)) (:foreground "Blue"))))
 '(font-lock-variable-name-face ((((class color) (background light)) (:foreground "blue"))))
 '(longlines-visible-face ((t (:foreground "red"))))
 '(p4-diff-del-face ((t (:foreground "DodgerBlue"))) t)
 '(p4-diff-head-face ((t (:background "black"))) t)
 '(p4-diff-ins-face ((t (:foreground "white"))) t)
 '(quack-threesemi-text-face ((((class color) (background light)) (:background "#c0ffff" :foreground "black" :weight bold)))))
